finished Part1
xdie44/PFMCPP_Project5 pull request #1
Opened 2020-09-14 21:12 UTC by xdie44

2020-09-14 21:14 UTC, xdie44 commented
I couldn't clear up the warning :"padding structure...."
How can I do that?

2020-09-15 03:39 UTC, matkatmusic requested changes

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +        int ChangeType(int whichOsc, int newType, int numOsc);
member functions should start with a lowercase letter.  Static functions should start with a capital letter.
- [ ] revise

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +        float duty, weight;
initialize these in-class, since your constructor doesn't do anything.
- [ ] revise

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +        char type;
initialize in-class
- [ ] revise

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +    return 1.1225f*freqTemp;
improve the readability.  add spaces around your `*`
- [ ] revise

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +    return oscType2;
put `if` bodies on their own line.
also, you can write this with a ternary expression:
```
return isTheSame ? oscType1 : oscType2;
```

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +    int  nHarm (float freq, float freqMax = 20000.0f);
capitalization of member function names.
- [ ] revise

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +}
fix the indentation here.  the style guide in the readme.md explains what it should be set to.
- [ ] revise.

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +    filterType = 'o';
- [ ] revise, coding style.

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +    }
put `if` bodies on their own line
- [ ] revise.

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +        int ChangeType(int whichLfo, int newType, int numLfo);
- [ ] revise.

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +    char ChangeLfoWave (char waveTypeIn = 'a', char waveTypeOut = 'b');
- [ ] revise.

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +    return true;
- [ ] revise.

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +    return waveTypeIn;
- [ ] revise.

2020-09-15 03:39 UTC, matkatmusic commented on main.cpp
> +     std::cout << std::endl;
group your if/else expressions by adding a blank line between them.  this will improve the readability.

- [ ] revise.

2020-09-16 06:13 UTC, matkatmusic requested changes

2020-09-16 06:13 UTC, matkatmusic commented on main.cpp
> +    else std::cout << "No Noise\n";
If you're going to use curly braces for the `if` block, use them for the `else` block as well.
It's easy to miss the `else` as part of a larger logic structure **at first glance** when you leave out the curly braces.   The code ends up looking generically like this when you leave them out:
```
if( expr )
{
   statements;
}
more statements;
```
compare that with:
```
if( expr )
{
   statements;
}
else
{
    statements;
}
```

consistency is key to making your code as readable as possible.
- [ ] revise

2020-09-16 21:54 UTC, matkatmusic approved these changes

2020-09-16 21:57 UTC, merged